[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Optional: Add environment variables for production
# [context.production.environment]
#   REACT_APP_SUPABASE_URL = "https://your-project.supabase.co"
#   REACT_APP_SUPABASE_ANON_KEY = "your-anon-key"
